// allProducts/home page
export const GET_ALL_PRODUCTS_REQUEST = '  PRODUCTS/GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = '  PRODUCTS/GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = '  PRODUCTS/GET_ALL_PRODUCTS_FAILURE';

//for admin only
export const ADD_PRODUCT_REQUEST = '   PRODUCTS/ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'PRODUCTS/ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = '   PRODUCTS/ADD_PRODUCT_FAILURE';

//for admin only
export const UPDATE_PRODUCT_REQUEST = 'PRODUCTS/UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'PRODUCTS/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'PRODUCTS/UPDATE_PRODUCT_FAILURE';

//for admin only
export const DELETE_PRODUCT_REQUEST = 'PRODUCTS/DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'PRODUCTS/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'PRODUCTS/DELETE_PRODUCT_FAILURE';